# Generated by Django 5.2.8 on 2025-11-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_flat_new_building'),
    ]

    def update_new_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            if flat.construction_year >= 2015:
                flat.new_building = True

    operations = [
        migrations.RunPython(update_new_building)
    ]
