# Generated by Django 5.2.8 on 2025-11-25 06:19

from django.db import migrations
import phonenumbers


def update_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        parsed_number = phonenumbers.parse(
            number=flat.owners_phonenumber,
            region='RU',
        )
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164
            )
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(update_pure_phone)
    ]
